server:
  port: 8443  # HTTPS를 8443에서 처리
  ssl:
    enabled: true  # SSL 활성화
    key-store: classpath:/static/config1/keystore.jks  # 키스토어 파일 경로
    key-store-password: 050924  # 키스토어 비밀번호
    key-store-type: PKCS12  # 키스토어 타입
    key-alias: jwt_key_alias  # 키 알리아스

  tomcat:
    additional-tls-connectors:
      - port: 8083  # HTTP 포트를 열어서 리디렉션 처리
        redirect-to-https: true  # HTTP 요청을 HTTPS로 리디렉션

spring:
  application:
    name: hotel-service  # 애플리케이션 이름
  
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: hr
    password: hr

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 41211a2d42ebba192243003ab70cacc9
            client-secret: PBFDPH3s6hvUPvvPOqhycFo6zYPW3a7n
            redirect-uri: "https://localhost:8443/oauth2/success"  # HTTPS로 리디렉션
            authorization-grant-type: authorization_code
          naver:  # 네이버 로그인 API 설정
            client-id: ZCu6SjlzSG3mKIvbTW1e
            client-secret: i9tNmWN5dX
            redirect-uri: "https://localhost:8443/naver/success"  # HTTPS로 리디렉션
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
            user-info-authentication-method: header
          naver:  # 네이버 로그인 API 제공자 설정
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response.id

  jwt:
    secret: your secret key
    expiration: 3600000

  mail:
    host: smtp.naver.com
    port: 587
    username: jho8719@naver.com # 네이버 이메일을 입력하세요
    password: 5G3TYJW8JZ34 # 네이버 비밀번호를 입력하세요
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.naver.com

logging:
  level:
    org: 
      springframework:
        security: DEBUG
    mybatis: DEBUG
    com:
      your:
        package: DEBUG
