server:
  port: 8083

spring:
  application:
    name: hotel-service  # 클라이언트 이름
  
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: hr
    password: hr
#		datasource:
#		    driver-class-name: oracle.jdbc.OracleDriver
#		    url: jdbc:oracle:thin:@192.168.2.63:1521/xe
#		    username: c##hr
#		    password: hr

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 41211a2d42ebba192243003ab70cacc9
            client-secret: PBFDPH3s6hvUPvvPOqhycFo6zYPW3a7n
            redirect-uri: "http://localhost:8083/oauth2/success"
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
            user-info-authentication-method: header

  jwt:
    secret: your secret key
    expiration: 3600000

  mail:
    host: smtp.naver.com
    port: 587
    username: jho8719@naver.com # 네이버 이메일을 입력하세요
    password: 5G3TYJW8JZ34 # 네이버 비밀번호를 입력하세요
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.naver.com

logging:
  level:
    org: 
      springframework:
        security: DEBUG
    mybatis: DEBUG
    com:
      your:
        package: DEBUG
